# Generated by Django 5.2.1 on 2025-05-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(default='TEMP', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_slug',
            field=models.CharField(default='TEMP', max_length=255, unique=True),
        ),
    ]
