# Generated by Django 5.2.1 on 2025-05-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_store', '0002_game_game_id_game_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_slug',
        ),
    ]
