# Generated by Django 5.2.1 on 2025-05-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_store', '0003_remove_game_game_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(default='TEMP', max_length=255),
        ),
    ]
